[package]
name = "kavach-config"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
regex = "1"
smart-default = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
