use std::collections::HashMap;

pub const DEFAULT_TOKEN_BUDGET: i32 = 180_000;
pub const DEFAULT_SUBAGENT_MAX_OUTPUT: i32 = 8_000;
pub const DEFAULT_SUBAGENT_TOTAL_CAP: i32 = 30_000;

#[derive(Debug, Clone)]
#[expect(clippy::exhaustive_structs, reason = "constructed at RPC boundary")]
#[expect(clippy::struct_excessive_bools, reason = "state machine flags")]
pub struct SessionState {
    pub id: String,
    pub session_id: String,
    pub today: String,
    pub project: String,
    pub work_dir: String,
    pub training_cutoff: String,
    pub research_done: bool,
    pub research_topics: Vec<String>,
    pub memory_queried: bool,
    pub post_compact: bool,
    pub compacted_at: String,
    pub compact_count: i32,
    pub turn_count: i32,
    pub last_reinforce_turn: i32,
    pub reinforce_every_n: i32,
    pub current_task: String,
    pub task_status: String,
    pub files_modified: Vec<String>,
    pub tasks_created: i32,
    pub tasks_completed: i32,
    pub task_list_id: String,
    pub intent_type: String,
    pub intent_domain: String,
    pub intent_skills: Vec<String>,
    pub specs_injected: Vec<String>,
    pub token_budget_total: i32,
    pub token_budget_used: i32,
    pub context_phase: String,
    pub active_subagents: i32,
    pub subagent_outputs: HashMap<String, i32>,
    pub subagent_max_output: i32,
    pub subagent_total_cap: i32,
    pub team_name: String,
    pub team_members: Vec<String>,
    pub active_teammates: i32,
    pub model_id: String,
    pub modules_injected: Vec<String>,
    pub last_failure_tool: String,
    pub last_failure_turn: i32,
    pub failure_block_count: i32,
    pub stop_reblock_count: i32,
    pub gates_fired_this_turn: i32,
    pub gates_fired_this_call: i32,
    pub last_seen_tool_use_id: String,
    pub last_advisory_gate: String,
    pub last_advisory_fix: String,
    pub last_progress_snapshot_turn: i32,
    pub last_progress_snapshot_writes: i32,
    pub last_progress_snapshot_db_writes: i32,
    pub last_review_files_count: usize,
    pub last_review_at: i64,
    pub failure_type: String,
    pub required_skills: Vec<String>,
    pub invoked_skills: Vec<String>,
    pub research_topic: String,
    pub last_subagent_turn: i32,
    pub subagent_action_pending: bool,
    pub subagent_action_turn: i32,
    pub recent_commands: Vec<String>,
    pub recent_tool_calls: Vec<String>,
    pub test_files_pending: Vec<String>,
    pub test_nudge_count: i32,
    pub case_facts: Vec<String>,
    pub intent_risk: String,
    pub subagent_files_read: i32,
    pub last_write_turn: i32,
    pub user_directive_turn: i32,
    pub new_crate_confirmed: bool,
    pub algo_hunter_invoked: bool,
    pub active_test_crates: Vec<String>,
    pub last_db_write_turn: i32,
    pub websearch_count_since_intent: i32,
    pub intent_set_turn: i32,
    pub think_first_injected: bool,
    pub files_modified_this_turn: Vec<String>,
    pub tdd_red_units: Vec<String>,
    pub lsp_diag_seen: Vec<String>,
    pub research_advisory_sent: bool,
    pub fanout_nudge_sent: bool,
    pub arch_skill_invoked: bool,
    pub gate_block_counts: HashMap<String, i32>,
    pub gate_circuit_breaker_threshold: i32,
    pub tripped_gate_categories: Vec<String>,
    pub current_phase: String,
    pub phase_start_turn: i32,
    pub current_iteration_file: String,
    pub iteration_files_done: Vec<String>,
    pub plan_done_files: Vec<String>,
    pub implement_done_files: Vec<String>,
    pub test_done_files: Vec<String>,
    pub harden_done_files: Vec<String>,
    pub current_kanban_card: String,
    pub loop_kanban_runnable: Option<u64>,
    pub blocked_cards: Vec<String>,
    pub user_focus: String,
    pub goal_state: String,
    pub goal_achieved: bool,
    pub goal_receipt_pass: bool,
    pub ai_verdict: Option<bool>,
    pub goal_set_turn: i32,
    pub loop_active: bool,
    pub loop_target: String,
    pub loop_iteration: i32,
    pub loop_max_iterations: i32,
    pub loop_start_turn: i32,
    pub rca_block_present: bool,
    pub rca_set_turn: i32,
    pub bounty_scan_signature: String,
    pub bounty_scan_clean: bool,
    pub subagent_files_written: Vec<String>,
    pub subagent_external_apis: Vec<String>,
    pub subagent_db_mutations: bool,
    pub subagent_denied_tools: Vec<String>,
    pub blast_escalation_threshold: i32,
    pub blast_escalated: bool,
    pub turn_shadow: String,
    pub turn_shadow_pending: bool,
    pub pending_advisories: Vec<String>,
    pub last_reward_summary: String,
    pub reward_session_pass: i32,
    pub reward_session_total: i32,
}
