use std::fmt::Write as _;

use clap::CommandFactory;

use crate::cli::Cli;

/// Full Markdown reference: every command, its flags/defaults, and examples.
#[must_use]
pub(crate) fn render() -> String {
    super::help_stack::on_big_stack(render_inner)
}

fn render_inner() -> String {
    let mut out = String::from("# kavach CLI reference\n\n_Generated by `kavach commands --markdown` — do not edit by hand._\n\n");
    let root = Cli::command();
    section(&root, "kavach", &mut out);
    out
}

fn section(cmd: &clap::Command, path: &str, out: &mut String) {
    writeln!(out, "## `{path}`\n").ok();
    if let Some(about) = cmd.get_about() {
        writeln!(out, "{about}\n").ok();
    }
    let args: Vec<&clap::Arg> = cmd.get_arguments().filter(|a| a.get_id() != "help").collect();
    if !args.is_empty() {
        out.push_str("| Flag | Description | Default |\n|---|---|---|\n");
        for a in args {
            out.push_str(&render::arg_row(a));
        }
        out.push('\n');
    }
    if let Some(after) = cmd.get_after_help() {
        writeln!(out, "```\n{after}\n```\n").ok();
    }
    let mut subs: Vec<&clap::Command> = cmd.get_subcommands().collect();
    subs.sort_by_key(|c| c.get_name().to_owned());
    for sub in subs {
        if sub.get_name() != "help" {
            section(sub, &format!("{path} {}", sub.get_name()), out);
        }
    }
}

mod render;

#[cfg(test)]
#[path = "help_md_test.rs"]
mod tests;
