// split: implementation-flow DAG — store-as-graph, render-Mermaid-on-read.
// A "flow" captures how an implementation has to proceed: an anchor entity
// (entity_type='flow') contains step entities (entity_type='flow_step') wired
// by `depends_on` edges. The DAG is the durable asset; Mermaid is a view
// generated by walking it (reuse the er.rs sanitize + string-build pattern).
//
// ARCH: ImplementationFlowDag
// PATTERN: store-as-DAG / render-on-read (Mermaid is a projection, not the store)
// SCOPE: scale (awareness read path; session-start injection)
// CAPACITY: <= ~200 steps/flow; flows/project small
// CONSISTENCY: upsert idempotent on (project, flow_key) + qualified step name
// FAILURE_MODE: cyclic depends_on -> rejected (fail closed); project missing -> NotFound
//
// SOURCE: https://surrealdb.com/docs/surrealql/statements/relate
// SOURCE: https://mermaid.js.org/syntax/flowchart.html
mod fetch;
mod model;
mod shape;
mod upsert;
#[cfg(test)]
#[path = "flow_dag_test.rs"]
#[path = "flow_dag_test.rs"]
mod tests;
pub use fetch::{fetch_flow, list_flows};
pub use model::{FlowDag, FlowEdgeInput, FlowSpec, FlowStep, FlowStepInput};
pub use shape::NodeShape;
pub use upsert::upsert_flow;
