// split: implementation-flow DAG — store-as-graph, render-Mermaid-on-read.
// A "flow" captures how an implementation has to proceed: an anchor entity
// (entity_type='flow') contains step entities (entity_type='flow_step') wired
// by `depends_on` edges. The DAG is the durable asset; Mermaid is a view
// generated by walking it (reuse the er.rs sanitize + string-build pattern).
//
// ARCH: ImplementationFlowDag
// PATTERN: store-as-DAG / render-on-read (Mermaid is a projection, not the store)
// SCOPE: scale (awareness read path; session-start injection)
// CAPACITY: <= ~200 steps/flow; flows/project small
// CONSISTENCY: upsert idempotent on (project, flow_key) + qualified step name
// FAILURE_MODE: cyclic depends_on -> rejected (fail closed); project missing -> NotFound
// TRADEOFF: structured ingest (no Mermaid parser); raw source cached for round-trip.
//
// SOURCE: https://surrealdb.com/docs/surrealql/statements/relate
// SOURCE: https://mermaid.js.org/syntax/flowchart.html
use crate::error::{Error, Result};
use crate::graph::dynamic::relate_dynamic;
use serde::{Deserialize, Serialize};
use surrealdb::Surreal;
use surrealdb::engine::local::Db;
use surrealdb_types::{RecordId, SurrealValue};

/// Mermaid node shape for a flow step. `Rect` is the default (`["label"]`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum NodeShape {
    /// `["label"]`
    #[default]
    Rect,
    /// `("label")`
    Round,
    /// `(["label"])`
    Stadium,
    /// `{"label"}`
    Diamond,
    /// `(("label"))`
    Circle,
}

impl NodeShape {
    /// Parse a shape hint; unknown values fall back to `Rect` (lenient ingest).
    #[must_use]
    pub fn parse(s: &str) -> Self {
        match s {
            "round" => Self::Round,
            "stadium" => Self::Stadium,
            "diamond" => Self::Diamond,
            "circle" => Self::Circle,
            _ => Self::Rect,
        }
    }

    /// The `snake_case` token persisted in `properties.shape`.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Rect => "rect",
            Self::Round => "round",
            Self::Stadium => "stadium",
            Self::Diamond => "diamond",
            Self::Circle => "circle",
        }
    }

    /// Wrap a (Mermaid-escaped) label in this shape's delimiters.
    fn wrap(self, label: &str) -> String {
        match self {
            Self::Rect => format!("[\"{label}\"]"),
            Self::Round => format!("(\"{label}\")"),
            Self::Stadium => format!("([\"{label}\"])"),
            Self::Diamond => format!("{{\"{label}\"}}"),
            Self::Circle => format!("((\"{label}\"))"),
        }
    }
}

/// Mermaid node ids reject hyphens / quotes / spaces — replace them, mirroring
/// the ER-diagram emitter (`cmd/db/pg/er.rs::sanitize`). A non-alphanumeric,
/// non-`_` char becomes `_` so the id is always a valid Mermaid identifier.
fn sanitize_id(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

/// Escape a label for inside a Mermaid quoted string: `"` would close the
/// string and `\n`/`\r` would break the line, so neutralize them.
fn escape_label(label: &str) -> String {
    label.replace('"', "&quot;").replace(['\n', '\r'], " ")
}

/// One step in a flow as supplied by the caller (structured ingest).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[expect(
    clippy::exhaustive_structs,
    reason = "cross-crate struct-literal DTO (kavach-rpc boundary); non_exhaustive => E0639"
)]
pub struct FlowStepInput {
    /// Caller-assigned id, unique within the flow (e.g. `"validate"`).
    pub step_id: String,
    /// Human label shown in the rendered node.
    pub label: String,
    /// Optional Mermaid shape hint; defaults to `Rect`.
    #[serde(default)]
    pub shape: Option<String>,
    /// Optional longer description (stored, not rendered into the node box).
    #[serde(default)]
    pub description: Option<String>,
}

/// One dependency edge: `from` is a prerequisite of `to`
/// (`from --depends_on--> to`; arrow points prerequisite → dependent).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[expect(
    clippy::exhaustive_structs,
    reason = "cross-crate struct-literal DTO (kavach-rpc boundary); non_exhaustive => E0639"
)]
pub struct FlowEdgeInput {
    /// `step_id` of the prerequisite.
    pub from: String,
    /// `step_id` of the dependent.
    pub to: String,
}

/// A full flow definition for upsert.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[expect(
    clippy::exhaustive_structs,
    reason = "cross-crate struct-literal DTO (kavach-rpc boundary); non_exhaustive => E0639"
)]
pub struct FlowSpec {
    /// Project-scoped key, unique per project (e.g. `"auth-flow"`).
    pub flow_key: String,
    /// Display title.
    pub flow_title: String,
    /// Steps (nodes).
    pub steps: Vec<FlowStepInput>,
    /// Dependency edges between steps.
    pub edges: Vec<FlowEdgeInput>,
    /// Optional raw Mermaid source cached for round-trip; never source of truth.
    #[serde(default)]
    pub raw_mermaid: Option<String>,
}

/// A resolved step node read back from the graph.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct FlowStep {
    /// Caller id within the flow.
    pub step_id: String,
    /// Display label.
    pub label: String,
    /// Shape hint.
    pub shape: NodeShape,
    /// Optional description.
    pub description: Option<String>,
}

/// The flow DAG read back from the graph: ordered steps + dependency edges.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[non_exhaustive]
pub struct FlowDag {
    /// Flow key.
    pub flow_key: String,
    /// Flow title.
    pub flow_title: String,
    /// Steps (nodes), in stored order.
    pub steps: Vec<FlowStep>,
    /// Dependency edges as `(from_step_id, to_step_id)`.
    pub edges: Vec<(String, String)>,
    /// Cached raw Mermaid source, if one was supplied at ingest.
    pub raw_mermaid: Option<String>,
}

impl FlowDag {
    /// Kahn topological sort over `depends_on` edges. Returns `Err(Cycle)` with
    /// the residual step ids when a cycle makes a full ordering impossible — a
    /// flow with a cycle is a contradiction (no step can be "first"), so we
    /// reject rather than render a misleading diagram.
    fn detect_cycle(&self) -> Option<Vec<String>> {
        use std::collections::{HashMap, VecDeque};
        let mut in_deg: HashMap<&str, usize> =
            self.steps.iter().map(|s| (s.step_id.as_str(), 0)).collect();
        let mut adj: HashMap<&str, Vec<&str>> = HashMap::new();
        for (from, to) in &self.edges {
            if !in_deg.contains_key(from.as_str()) || !in_deg.contains_key(to.as_str()) {
                continue;
            }
            adj.entry(from.as_str()).or_default().push(to.as_str());
            let d = in_deg.entry(to.as_str()).or_insert(0);
            *d = d.saturating_add(1);
        }
        let mut queue: VecDeque<&str> = in_deg
            .iter()
            .filter(|&(_, &d)| d == 0)
            .map(|(&k, _)| k)
            .collect();
        let mut seen = 0usize;
        while let Some(n) = queue.pop_front() {
            seen = seen.saturating_add(1);
            if let Some(succ) = adj.get(n) {
                for &m in succ {
                    if let Some(d) = in_deg.get_mut(m) {
                        *d = d.saturating_sub(1);
                        if *d == 0 {
                            queue.push_back(m);
                        }
                    }
                }
            }
        }
        if seen == self.steps.len() {
            None
        } else {
            Some(
                in_deg
                    .iter()
                    .filter(|&(_, &d)| d > 0)
                    .map(|(&k, _)| k.to_owned())
                    .collect(),
            )
        }
    }

    /// Render this DAG as a Mermaid `flowchart TD`. Steps emit as shaped nodes;
    /// each dependency edge emits as `from --> to`. Node ids are sanitized so
    /// the output is always valid Mermaid even for hostile step ids/labels.
    #[must_use]
    pub fn to_mermaid(&self) -> String {
        let mut out = String::from("flowchart TD\n");
        for step in &self.steps {
            let id = sanitize_id(&step.step_id);
            let label = escape_label(&step.label);
            out.push_str("  ");
            out.push_str(&id);
            out.push_str(&step.shape.wrap(&label));
            out.push('\n');
        }
        for (from, to) in &self.edges {
            out.push_str("  ");
            out.push_str(&sanitize_id(from));
            out.push_str(" --> ");
            out.push_str(&sanitize_id(to));
            out.push('\n');
        }
        out
    }
}

#[derive(SurrealValue)]
struct EntityIdRow {
    id: RecordId,
}

#[derive(SurrealValue)]
struct ProjectIdRow {
    id: RecordId,
}

/// Resolve a project slug to its record id, or `Err(RecordNotFound)`.
async fn project_id(db: &Surreal<Db>, project_slug: &str) -> Result<RecordId> {
    let q = "SELECT id FROM project WHERE slug = $slug LIMIT 1";
    let mut resp = db
        .query(q)
        .bind(("slug", project_slug.to_owned()))
        .await?;
    let row: Option<ProjectIdRow> = resp.take(0)?;
    row.map(|r| r.id)
        .ok_or_else(|| Error::RecordNotFound(format!("project '{project_slug}' not registered")))
}

/// Upsert an entity carrying `properties` and `project`, keyed on
/// (`entity_type`, `name`). Updates the row in place if it exists so re-ingest
/// of the same flow is idempotent. Returns the entity id.
async fn upsert_entity_props(
    db: &Surreal<Db>,
    entity_type: &str,
    name: &str,
    project: &RecordId,
    properties: serde_json::Value,
) -> Result<RecordId> {
    let find_q = "SELECT id FROM entity WHERE entity_type = $type AND name = $name LIMIT 1";
    let mut resp = db
        .query(find_q)
        .bind(("type", entity_type.to_owned()))
        .bind(("name", name.to_owned()))
        .await?;
    let existing: Option<EntityIdRow> = resp.take(0)?;
    if let Some(row) = existing {
        let upd = "UPDATE $id SET properties = $props, project = $project RETURN id";
        let mut r = db
            .query(upd)
            .bind(("id", row.id.clone()))
            .bind(("props", properties))
            .bind(("project", project.clone()))
            .await?;
        let updated: Option<EntityIdRow> = r.take(0)?;
        return Ok(updated.map_or(row.id, |u| u.id));
    }
    let create_q = "CREATE entity SET entity_type = $type, name = $name, \
                    properties = $props, project = $project RETURN id";
    let mut cresp = db
        .query(create_q)
        .bind(("type", entity_type.to_owned()))
        .bind(("name", name.to_owned()))
        .bind(("props", properties))
        .bind(("project", project.clone()))
        .await?;
    let row: Option<EntityIdRow> = cresp.take(0)?;
    row.map(|r| r.id)
        .ok_or_else(|| Error::RecordNotFound("flow entity create returned no id".into()))
}

/// Fully-qualified, globally-unique step entity name: `flow_step:{slug}/{flow}/{step}`.
/// The `entity` unique index is on (`entity_type`, `name`), so the name must
/// disambiguate across projects and flows.
fn step_name(project_slug: &str, flow_key: &str, step_id: &str) -> String {
    format!("{project_slug}/{flow_key}/{step_id}")
}

/// The flow anchor entity name: `{slug}/{flow_key}`.
fn flow_name(project_slug: &str, flow_key: &str) -> String {
    format!("{project_slug}/{flow_key}")
}

/// Upsert a flow: anchor + steps + `depends_on` edges. Rejects a cyclic flow
/// before writing edges (fail closed). Idempotent on re-ingest.
///
/// # Errors
/// - `Error::RecordNotFound` if the project is not registered.
/// - `Error::Migration` if the supplied edges form a cycle, or reference an
///   unknown `step_id`.
/// - `Error::Surreal` on any underlying query failure.
pub async fn upsert_flow(db: &Surreal<Db>, project_slug: &str, spec: &FlowSpec) -> Result<RecordId> {
    // Validate edges reference known steps + are acyclic BEFORE any write.
    let known: std::collections::HashSet<&str> =
        spec.steps.iter().map(|s| s.step_id.as_str()).collect();
    for e in &spec.edges {
        if !known.contains(e.from.as_str()) || !known.contains(e.to.as_str()) {
            return Err(Error::Migration(format!(
                "flow '{}' edge {}->{} references unknown step",
                spec.flow_key, e.from, e.to
            )));
        }
    }
    let probe = FlowDag {
        flow_key: spec.flow_key.clone(),
        flow_title: spec.flow_title.clone(),
        steps: spec
            .steps
            .iter()
            .map(|s| FlowStep {
                step_id: s.step_id.clone(),
                label: s.label.clone(),
                shape: s.shape.as_deref().map_or(NodeShape::Rect, NodeShape::parse),
                description: s.description.clone(),
            })
            .collect(),
        edges: spec
            .edges
            .iter()
            .map(|e| (e.from.clone(), e.to.clone()))
            .collect(),
        raw_mermaid: spec.raw_mermaid.clone(),
    };
    if let Some(cycle) = probe.detect_cycle() {
        return Err(Error::Migration(format!(
            "flow '{}' has a dependency cycle among steps: {}",
            spec.flow_key,
            cycle.join(", ")
        )));
    }

    let pid = project_id(db, project_slug).await?;

    let anchor_props = serde_json::json!({
        "flow_key": spec.flow_key,
        "flow_title": spec.flow_title,
        "raw_mermaid": spec.raw_mermaid,
    });
    let anchor_id = upsert_entity_props(
        db,
        "flow",
        &flow_name(project_slug, &spec.flow_key),
        &pid,
        anchor_props,
    )
    .await?;

    // Re-ingest idempotency: entities upsert by name, but RELATE always inserts
    // a NEW edge — so without this, re-ingesting the same flow duplicates every
    // `contains`/`depends_on` edge. Delete the anchor's existing `contains`
    // edges and the `depends_on` edges OUT of its current step set, traversing
    // from the anchor record (NOT a `string::starts_with` scan over the whole
    // `entity` table — that is an unindexed full scan that blocks on a large DB
    // and trips the 2s RPC read timeout; rca.flow-upsert-entity-scan-timeout).
    // Single round-trip, both edge classes, scoped to this flow's own nodes.
    db.query(
        "LET $steps = (SELECT VALUE out FROM $anchor->contains); \
         DELETE depends_on WHERE in IN $steps; \
         DELETE contains WHERE in = $anchor;",
    )
    .bind(("anchor", anchor_id.clone()))
    .await?;

    let mut step_ids: std::collections::HashMap<&str, RecordId> = std::collections::HashMap::new();
    for s in &spec.steps {
        let shape = s.shape.as_deref().map_or(NodeShape::Rect, NodeShape::parse);
        let props = serde_json::json!({
            "flow_key": spec.flow_key,
            "step_id": s.step_id,
            "label": s.label,
            "shape": shape.as_str(),
            "description": s.description,
        });
        let id = upsert_entity_props(
            db,
            "flow_step",
            &step_name(project_slug, &spec.flow_key, &s.step_id),
            &pid,
            props,
        )
        .await?;
        // anchor --contains--> step
        relate_dynamic(db, &anchor_id, &id, "contains", 1.0).await?;
        step_ids.insert(s.step_id.as_str(), id);
    }

    for e in &spec.edges {
        // Both endpoints guaranteed present by the validation pass above.
        if let (Some(from), Some(to)) = (step_ids.get(e.from.as_str()), step_ids.get(e.to.as_str()))
        {
            relate_dynamic(db, from, to, "depends_on", 1.0).await?;
        }
    }

    Ok(anchor_id)
}

#[derive(SurrealValue)]
struct AnchorRow {
    properties: Option<serde_json::Value>,
}

#[derive(SurrealValue)]
struct StepRow {
    name: String,
    properties: Option<serde_json::Value>,
}

/// `depends_on` edge projection keyed by `step_id` (stable across re-ingest).
#[derive(SurrealValue)]
struct FlowEdgeRow {
    from_step: Option<String>,
    to_steps: Vec<String>,
}

fn prop_str(props: Option<&serde_json::Value>, key: &str) -> Option<String> {
    props
        .and_then(|v| v.get(key))
        .and_then(serde_json::Value::as_str)
        .map(ToOwned::to_owned)
}

/// Fetch a flow's DAG (anchor metadata + steps + `depends_on` edges).
///
/// # Errors
/// - `Error::RecordNotFound` if the project or the flow does not exist.
/// - `Error::Surreal` on query failure.
pub async fn fetch_flow(db: &Surreal<Db>, project_slug: &str, flow_key: &str) -> Result<FlowDag> {
    let anchor_name = flow_name(project_slug, flow_key);
    let aq = "SELECT properties FROM entity \
              WHERE entity_type = 'flow' AND name = $name LIMIT 1";
    let mut aresp = db
        .query(aq)
        .bind(("name", anchor_name.clone()))
        .await?;
    let anchor: Option<AnchorRow> = aresp.take(0)?;
    let Some(anchor) = anchor else {
        return Err(Error::RecordNotFound(format!(
            "flow '{flow_key}' not found in project '{project_slug}'"
        )));
    };

    let prefix = format!("{project_slug}/{flow_key}/");
    let sq = "SELECT name, properties FROM entity \
              WHERE entity_type = 'flow_step' AND string::starts_with(name, $prefix)";
    let mut sresp = db.query(sq).bind(("prefix", prefix.clone())).await?;
    let rows: Vec<StepRow> = sresp.take(0)?;

    let mut steps: Vec<FlowStep> = Vec::with_capacity(rows.len());
    let mut edges: Vec<(String, String)> = Vec::new();
    for row in &rows {
        let step_id = prop_str(row.properties.as_ref(), "step_id").unwrap_or_else(|| {
            row.name
                .rsplit('/')
                .next()
                .unwrap_or(row.name.as_str())
                .to_owned()
        });
        let label = prop_str(row.properties.as_ref(), "label").unwrap_or_else(|| step_id.clone());
        let shape = prop_str(row.properties.as_ref(), "shape")
            .map_or(NodeShape::Rect, |s| NodeShape::parse(&s));
        let description = prop_str(row.properties.as_ref(), "description");
        steps.push(FlowStep {
            step_id,
            label,
            shape,
            description,
        });
    }

    // Re-query edges keyed by step_id: traverse depends_on, mapping target
    // entity names back to their step_id via the prefix. Done as a second pass
    // so edge endpoints are step_ids (stable across re-ingest), not record ids.
    let eq = "SELECT properties.step_id AS from_step, \
              ->depends_on->entity.properties.step_id AS to_steps \
              FROM entity \
              WHERE entity_type = 'flow_step' AND string::starts_with(name, $prefix)";
    let mut eresp = db.query(eq).bind(("prefix", prefix.clone())).await?;
    let erows: Vec<FlowEdgeRow> = eresp.take(0)?;
    for er in erows {
        if let Some(from) = er.from_step {
            for to in er.to_steps {
                edges.push((from.clone(), to));
            }
        }
    }

    Ok(FlowDag {
        flow_key: flow_key.to_owned(),
        flow_title: prop_str(anchor.properties.as_ref(), "flow_title")
            .unwrap_or_else(|| flow_key.to_owned()),
        steps,
        edges,
        raw_mermaid: prop_str(anchor.properties.as_ref(), "raw_mermaid"),
    })
}

/// List the flow keys + titles defined for a project (for awareness injection).
///
/// # Errors
/// `Error::Surreal` on query failure.
pub async fn list_flows(db: &Surreal<Db>, project_slug: &str) -> Result<Vec<(String, String)>> {
    let prefix = format!("{project_slug}/");
    let q = "SELECT properties FROM entity \
             WHERE entity_type = 'flow' AND string::starts_with(name, $prefix)";
    let mut resp = db.query(q).bind(("prefix", prefix)).await?;
    let rows: Vec<AnchorRow> = resp.take(0)?;
    let mut out = Vec::with_capacity(rows.len());
    for row in rows {
        if let Some(key) = prop_str(row.properties.as_ref(), "flow_key") {
            let title =
                prop_str(row.properties.as_ref(), "flow_title").unwrap_or_else(|| key.clone());
            out.push((key, title));
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> FlowDag {
        FlowDag {
            flow_key: "auth".to_owned(),
            flow_title: "Auth Flow".to_owned(),
            steps: vec![
                FlowStep {
                    step_id: "validate".to_owned(),
                    label: "Validate input".to_owned(),
                    shape: NodeShape::Rect,
                    description: None,
                },
                FlowStep {
                    step_id: "issue-token".to_owned(),
                    label: "Issue \"token\"".to_owned(),
                    shape: NodeShape::Diamond,
                    description: Some("mint PASETO".to_owned()),
                },
            ],
            edges: vec![("validate".to_owned(), "issue-token".to_owned())],
            raw_mermaid: None,
        }
    }

    #[test]
    fn mermaid_sanitizes_ids_and_escapes_labels() {
        let m = sample().to_mermaid();
        assert!(m.starts_with("flowchart TD\n"), "header: {m}");
        // hyphen in step_id becomes _ in the node id
        assert!(m.contains("issue_token{\"Issue &quot;token&quot;\"}"), "{m}");
        assert!(m.contains("validate[\"Validate input\"]"), "{m}");
        // edge uses sanitized ids
        assert!(m.contains("validate --> issue_token"), "{m}");
    }

    #[test]
    fn detect_cycle_flags_a_cycle() {
        let mut dag = sample();
        // add reverse edge -> 2-cycle
        dag.edges.push(("issue-token".to_owned(), "validate".to_owned()));
        let cycle = dag.detect_cycle().expect("should detect cycle");
        assert_eq!(cycle.len(), 2, "both steps are in the cycle: {cycle:?}");
    }

    #[test]
    fn detect_cycle_accepts_a_dag() {
        assert!(sample().detect_cycle().is_none());
    }

    #[test]
    fn shape_roundtrips_through_str() {
        for s in [
            NodeShape::Rect,
            NodeShape::Round,
            NodeShape::Stadium,
            NodeShape::Diamond,
            NodeShape::Circle,
        ] {
            assert_eq!(NodeShape::parse(s.as_str()), s);
        }
        assert_eq!(NodeShape::parse("nonsense"), NodeShape::Rect);
    }

    fn spec() -> FlowSpec {
        FlowSpec {
            flow_key: "auth".to_owned(),
            flow_title: "Auth Flow".to_owned(),
            steps: vec![
                FlowStepInput {
                    step_id: "validate".to_owned(),
                    label: "Validate input".to_owned(),
                    shape: Some("rect".to_owned()),
                    description: None,
                },
                FlowStepInput {
                    step_id: "issue".to_owned(),
                    label: "Issue token".to_owned(),
                    shape: Some("diamond".to_owned()),
                    description: Some("mint PASETO".to_owned()),
                },
            ],
            edges: vec![FlowEdgeInput {
                from: "validate".to_owned(),
                to: "issue".to_owned(),
            }],
            raw_mermaid: None,
        }
    }

    async fn db_with_project() -> Surreal<Db> {
        let db = crate::open_memory().await.expect("open in-memory db");
        crate::apply_schema(&db).await.expect("schema");
        db.query("CREATE project SET slug = 'p', display = 'P', workdir = '/tmp'")
            .await
            .expect("create project");
        db
    }

    fn keyset(dag: &FlowDag) -> (Vec<String>, Vec<(String, String)>) {
        let mut steps: Vec<String> = dag.steps.iter().map(|s| s.step_id.clone()).collect();
        steps.sort();
        let mut edges = dag.edges.clone();
        edges.sort();
        (steps, edges)
    }

    #[tokio::test]
    async fn roundtrip_ingest_render_reingest_is_stable() {
        let db = db_with_project().await;
        upsert_flow(&db, "p", &spec()).await.expect("first upsert");
        let dag1 = fetch_flow(&db, "p", "auth").await.expect("fetch 1");
        // render is non-empty Mermaid with both nodes + the edge
        let m = dag1.to_mermaid();
        assert!(m.contains("validate[\"Validate input\"]"), "{m}");
        assert!(m.contains("issue{\"Issue token\"}"), "{m}");
        assert!(m.contains("validate --> issue"), "{m}");

        // Re-ingest the SAME spec — idempotent: identical node + edge sets.
        upsert_flow(&db, "p", &spec()).await.expect("second upsert");
        let dag2 = fetch_flow(&db, "p", "auth").await.expect("fetch 2");
        assert_eq!(keyset(&dag1), keyset(&dag2), "round-trip is stable");
        assert_eq!(dag2.steps.len(), 2, "no duplicate steps on re-ingest");
    }

    #[tokio::test]
    async fn upsert_rejects_a_cycle_before_writing() {
        let db = db_with_project().await;
        let mut s = spec();
        s.edges.push(FlowEdgeInput {
            from: "issue".to_owned(),
            to: "validate".to_owned(),
        });
        let err = upsert_flow(&db, "p", &s).await.expect_err("cycle rejected");
        assert!(format!("{err}").contains("cycle"), "{err}");
        // fail closed: nothing persisted.
        assert!(fetch_flow(&db, "p", "auth").await.is_err(), "no anchor written");
    }

    #[tokio::test]
    async fn upsert_rejects_edge_to_unknown_step() {
        let db = db_with_project().await;
        let mut s = spec();
        s.edges.push(FlowEdgeInput {
            from: "validate".to_owned(),
            to: "ghost".to_owned(),
        });
        let err = upsert_flow(&db, "p", &s).await.expect_err("unknown step");
        assert!(format!("{err}").contains("unknown step"), "{err}");
    }

    #[tokio::test]
    async fn upsert_rejects_unregistered_project() {
        let db = crate::open_memory().await.expect("open in-memory db");
        crate::apply_schema(&db).await.expect("schema");
        let err = upsert_flow(&db, "nope", &spec())
            .await
            .expect_err("unregistered project");
        assert!(format!("{err}").contains("not registered"), "{err}");
    }
}
