// Pattern 1 — Classify and Act. A classifier agent reads the objective, picks
// one of the declared routes, then dispatches the matching specialist. Routing
// happens in an isolated context so the classifier never does the downstream work.
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · Anthropic agent-design patterns.
use super::escape::js_str;
use super::model_tier::{Role, agent_opts};
use crate::cmd::goal::loop_yaml::GoalLoopYaml;

/// Upper bound on emitted routes — a runaway YAML list must not balloon the
/// generated workflow or the classifier's enum. Excess routes are dropped.
const MAX_ROUTES: usize = 32;

/// Render the Pattern-1 classify-and-act harness over `routes`.
pub(super) fn emit(g: &GoalLoopYaml, routes: &[String]) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    // Classification is a routing DECISION (brain); the specialist Act is a doer.
    let classify_opts = agent_opts("Classify", Role::Brain);
    let act_opts = agent_opts("Act", Role::Doer);
    // Each route becomes a JS string literal in the choices array, bounded so a
    // pathological YAML list cannot blow up the generated source.
    let route_arr = routes
        .iter()
        .take(MAX_ROUTES)
        .map(|r| js_str(r))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r"export const meta = {{
  name: 'classify-act',
  description: 'Classify the objective, then dispatch the matching specialist',
  phases: [{{ title: 'Classify' }}, {{ title: 'Act' }}],
}}

// Generated by `kavach goal compile`. DO NOT hand-edit; regenerate from loop.yaml.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const ROUTES = [{route_arr}]

const ROUTE_SCHEMA = {{
  type: 'object', additionalProperties: false, required: ['route'],
  properties: {{ route: {{ enum: ROUTES }} }},
}}

// CLASSIFY: a single agent picks exactly one route from the declared set.
const decision = await agent(
  `Classify this objective into one of ${{JSON.stringify(ROUTES)}}: ${{INTENT}}`,
  {{ {classify_opts}, schema: ROUTE_SCHEMA }})

const chosen = decision && decision.route ? decision.route : ROUTES[0]

// ACT: dispatch the specialist for the chosen route, gated by the oracle.
const result = await agent(
  `You are the '${{chosen}}' specialist. Handle: ${{INTENT}}. Make this pass: ${{ORACLE_CHECK}}`,
  {{ {act_opts} }})

return {{ goal_id: GOAL_ID, route: chosen, result }}
"
    )
}
