// Pattern 2 — Fan Out and Synthesize. Split the work across N isolated shards
// that cannot contaminate one another, then a synthesis barrier merges every
// shard into one artifact. The `parallel()` call is the barrier.
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · Anthropic agent-design patterns.
use super::escape::js_str;
use super::model_tier::{Role, agent_opts};
use crate::cmd::goal::loop_yaml::GoalLoopYaml;

/// Hard ceiling on fan-out width — caps worst-case token spend per goal. The
/// runtime `budget.remaining()` floor is the live brake; this is the structural
/// backstop so untrusted YAML cannot generate absurd fan-out. See arch report.
const MAX_SHARDS: u32 = 64;

/// Render the Pattern-2 fan-out/synthesize harness across `shards`.
pub(super) fn emit(g: &GoalLoopYaml, shards: u32) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    let n = shards.clamp(1, MAX_SHARDS);
    // Shards are doers (cheap tier); the synthesis is brain work (frontier).
    let fanout_opts = agent_opts("FanOut", Role::Doer);
    let synth_opts = agent_opts("Synthesize", Role::Brain);

    format!(
        r"export const meta = {{
  name: 'fan-out-synthesize',
  description: 'Shard the work across isolated agents, then synthesize one artifact',
  phases: [{{ title: 'FanOut' }}, {{ title: 'Synthesize' }}],
}}

// Generated by `kavach goal compile`. DO NOT hand-edit; regenerate from loop.yaml.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const SHARDS = {n}

// FAN OUT: each shard runs in its own clean context (barrier — collect all).
const shardResults = (await parallel(
  Array.from({{ length: SHARDS }}, (_, i) => () =>
    agent(`Shard ${{i + 1}}/${{SHARDS}} of: ${{INTENT}}. Work only your slice; ignore the rest.`,
          {{ {fanout_opts} }}))
)).filter(Boolean)

// SYNTHESIZE: one agent merges every shard, gated by the oracle.
const merged = await agent(
  `Merge these ${{shardResults.length}} shard outputs into one coherent result for: ${{INTENT}}.\n` +
  `It must satisfy: ${{ORACLE_CHECK}}\n\n` + shardResults.map((r, i) => `--- shard ${{i + 1}} ---\n${{r}}`).join('\n'),
  {{ {synth_opts} }})

return {{ goal_id: GOAL_ID, shards: shardResults.length, merged }}
"
    )
}
