// Pattern 4 — Generate and Filter. Generate a pile of candidate artifacts, then
// pass them through a strict verifier/dedup so only oracle-passing survivors
// remain. Ideal where taste/naming/design matters and one shot is unreliable.
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · Anthropic agent-design patterns.
use super::escape::js_str;
use crate::cmd::goal::loop_yaml::GoalLoopYaml;

/// Ceiling on candidate count — bounds generation spend.
const MAX_CANDIDATES: u32 = 64;

/// Render the Pattern-4 generate/filter harness over `candidates`.
pub(super) fn emit(g: &GoalLoopYaml, candidates: u32) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    let n = candidates.clamp(1, MAX_CANDIDATES);

    format!(
        r"export const meta = {{
  name: 'generate-filter',
  description: 'Generate many candidates, then filter to oracle-passing survivors',
  phases: [{{ title: 'Generate' }}, {{ title: 'Filter' }}],
}}

// Generated by `kavach goal compile`. DO NOT hand-edit; regenerate from loop.yaml.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const CANDIDATES = {n}

const FILTER_SCHEMA = {{
  type: 'object', additionalProperties: false, required: ['keep', 'candidate'],
  properties: {{ keep: {{ type: 'boolean' }}, candidate: {{ type: 'string' }} }},
}}

// GENERATE then FILTER per candidate — pipeline so a candidate is filtered the
// instant it is generated, no barrier between the two stages.
const judged = await pipeline(
  Array.from({{ length: CANDIDATES }}, (_, i) => i),
  (i) => agent(`Generate distinct candidate ${{i + 1}}/${{CANDIDATES}} for: ${{INTENT}}`,
               {{ phase: 'Generate' }}),
  (candidate) => agent(`Does this candidate satisfy ${{ORACLE_CHECK}}? Set keep accordingly.\n\n${{candidate}}`,
                       {{ phase: 'Filter', schema: FILTER_SCHEMA }})
)

// Dedup survivors by exact candidate text.
const seen = new Set()
const survivors = []
for (const j of judged.filter(Boolean)) {{
  if (j.keep && !seen.has(j.candidate)) {{ seen.add(j.candidate); survivors.push(j.candidate) }}
}}

return {{ goal_id: GOAL_ID, generated: CANDIDATES, survivors }}
"
    )
}
