// Pattern 6 — Loop Until Done. The original oracle-gated loop: work, verify,
// fan out diagnostics on a failed attempt, until the oracle passes or the
// attempt/budget limits run out. Cures agentic laziness (finishes on criteria,
// not on a tired context window).
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · decision.goal-oracle-workflow.
use super::escape::js_str;
use crate::cmd::goal::loop_yaml::{GoalLoopYaml, OnMaxAttempts};

impl OnMaxAttempts {
    /// The JS branch body that runs when attempts are exhausted.
    pub(super) const fn js_branch(self) -> &'static str {
        match self {
            Self::Escalate => {
                "log(`ESCALATE: ${MAX} attempts exhausted without a passing oracle for ${GOAL_ID}`)"
            }
            Self::Fail => "log(`FAIL: goal ${GOAL_ID} unmet after ${MAX} attempts`)",
            Self::WaitManualApproval => {
                "log(`AWAITING APPROVAL: ${GOAL_ID} paused — run kavach goal approve`)"
            }
        }
    }
}

/// Render the Pattern-6 oracle loop.
pub(super) fn emit(g: &GoalLoopYaml) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    let max = g.loop_limits.max_attempts;
    let floor = g.loop_limits.budget_floor;
    let diag = g.loop_limits.parallel_diagnostics;
    let on_max = g.loop_limits.on_max_attempts.js_branch();

    let lenses: Vec<String> = (0..diag).map(|i| format!("'lens-{i}'")).collect();
    let lens_arr = lenses.join(", ");

    format!(
        r#"export const meta = {{
  name: 'goal-loop',
  description: 'Oracle-gated loop until the check passes or attempts/budget run out',
  phases: [{{ title: 'Work' }}, {{ title: 'Verify' }}, {{ title: 'Diagnose' }}],
}}

// Generated by `kavach goal compile` from .kavach/goals/<id>/loop.yaml.
// DO NOT hand-edit; regenerate from the YAML source of truth.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const MAX = {max}
const BUDGET_FLOOR = {floor}

const RECEIPT_SCHEMA = {{
  type: 'object', additionalProperties: false,
  required: ['oracle_result', 'exit_code', 'output'],
  properties: {{
    oracle_result: {{ enum: ['pass', 'fail'] }},
    exit_code: {{ type: 'integer' }},
    output: {{ type: 'string' }},
  }},
}}

let receipt = null
let attempt = 0
while (attempt < MAX && budget.remaining() > BUDGET_FLOOR) {{
  attempt++

  // WORK: a worker tries to make the oracle pass.
  await agent(`Attempt ${{attempt}}/${{MAX}}: ${{INTENT}}. Make this pass: ${{ORACLE_CHECK}}`,
              {{ phase: 'Work' }})

  // VERIFY: run the oracle. Its exit code is the proof. The same agent records
  // the receipt in SurrealDB via the kavach CLI — the stop gate reads it back.
  receipt = await agent(
    `Run exactly: ${{ORACLE_CHECK}}\n` +
    `Capture exit code + output, then record the receipt:\n` +
    `  kavach db event --type goal_loop_attempt --project ${{GOAL_ID}} \\\n` +
    `    --payload '{{"goal_id":"${{GOAL_ID}}","attempt":${{attempt}},"oracle_result":"<pass|fail>"}}'\n` +
    `Return the structured result.`,
    {{ phase: 'Verify', schema: RECEIPT_SCHEMA }}
  )

  if (receipt && receipt.oracle_result === 'pass') break

  // DIAGNOSE: fan out independent root-cause hunters on a failed attempt.
  await parallel([{lens_arr}].map((lens) => () =>
    agent(`Oracle failed (exit ${{receipt ? receipt.exit_code : '?'}}). Diagnose from the ${{lens}} angle.`,
          {{ phase: 'Diagnose' }})))
}}

if (!(receipt && receipt.oracle_result === 'pass')) {{
  {on_max}
}}

return {{ goal_id: GOAL_ID, achieved: !!(receipt && receipt.oracle_result === 'pass'), attempts: attempt }}
"#
    )
}
