// Pattern 5 — Pairwise Tournament. N agents each solve the same problem a
// different way; a judge compares two head-to-head and the winner advances,
// until one champion remains. LLMs judge head-to-head far more reliably than
// they assign absolute scores, and this sorts more items than fit one prompt.
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · Anthropic agent-design patterns.
use super::escape::js_str;
use crate::cmd::goal::loop_yaml::GoalLoopYaml;

/// Ceiling on bracket size — bounds total judge comparisons (N-1 matches).
const MAX_COMPETITORS: u32 = 64;

/// Render the Pattern-5 pairwise-tournament harness over `competitors`.
pub(super) fn emit(g: &GoalLoopYaml, competitors: u32) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    let n = competitors.clamp(2, MAX_COMPETITORS);

    format!(
        r"export const meta = {{
  name: 'pairwise-tournament',
  description: 'N solutions enter; a judge advances winners head-to-head until one champion',
  phases: [{{ title: 'Compete' }}, {{ title: 'Judge' }}],
}}

// Generated by `kavach goal compile`. DO NOT hand-edit; regenerate from loop.yaml.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const COMPETITORS = {n}

const JUDGE_SCHEMA = {{
  type: 'object', additionalProperties: false, required: ['winner'],
  properties: {{ winner: {{ enum: ['a', 'b'] }} }},
}}

// COMPETE: each entrant solves the problem its own way (barrier — need all).
let bracket = (await parallel(
  Array.from({{ length: COMPETITORS }}, (_, i) => () =>
    agent(`Entrant ${{i + 1}}/${{COMPETITORS}}: solve ${{INTENT}} via a DISTINCT approach. Target: ${{ORACLE_CHECK}}`,
          {{ phase: 'Compete' }}))
)).filter(Boolean)

// JUDGE: single-elimination. Each round pairs entrants; the judge picks a winner
// per pair against the oracle rubric. Odd entrant byes to the next round.
while (bracket.length > 1) {{
  const next = []
  for (let i = 0; i < bracket.length; i += 2) {{
    if (i + 1 >= bracket.length) {{ next.push(bracket[i]); break }}
    const a = bracket[i], b = bracket[i + 1]
    const verdict = await agent(
      `Judge against ${{ORACLE_CHECK}}. Pick the stronger: 'a' or 'b'.\n\n[a]\n${{a}}\n\n[b]\n${{b}}`,
      {{ phase: 'Judge', schema: JUDGE_SCHEMA }})
    next.push(verdict && verdict.winner === 'b' ? b : a)
  }}
  bracket = next
}}

return {{ goal_id: GOAL_ID, entrants: COMPETITORS, champion: bracket.length ? bracket[0] : null }}
"
    )
}
