// Pattern 3 — Worker and Critic (adversarial). A worker produces an artifact;
// N independent critics, each in a clean context with no attachment to the
// generation, grade it against the oracle. Majority decides. This is the direct
// cure for self-referential bias.
//
// SOURCE: youtube.com/watch?v=l5rae4LMKBc · Anthropic agent-design patterns.
use super::escape::js_str;
use crate::cmd::goal::loop_yaml::GoalLoopYaml;

/// Ceiling on critic count — an odd-friendly bound; majority needs few voters.
const MAX_CRITICS: u32 = 16;

/// Render the Pattern-3 worker/critic harness with `critics` adversarial votes.
pub(super) fn emit(g: &GoalLoopYaml, critics: u32) -> String {
    let goal = js_str(&g.goal_id);
    let intent = js_str(&g.intent);
    let check = js_str(g.oracle.check_str());
    let n = critics.clamp(1, MAX_CRITICS);

    format!(
        r"export const meta = {{
  name: 'worker-critic',
  description: 'Worker produces an artifact; independent critics adversarially grade it',
  phases: [{{ title: 'Work' }}, {{ title: 'Critique' }}],
}}

// Generated by `kavach goal compile`. DO NOT hand-edit; regenerate from loop.yaml.
const GOAL_ID = {goal}
const INTENT = {intent}
const ORACLE_CHECK = {check}
const CRITICS = {n}

const VERDICT_SCHEMA = {{
  type: 'object', additionalProperties: false, required: ['approved', 'reason'],
  properties: {{ approved: {{ type: 'boolean' }}, reason: {{ type: 'string' }} }},
}}

// WORK: produce the artifact.
const artifact = await agent(`Produce the artifact for: ${{INTENT}}. Target: ${{ORACLE_CHECK}}`,
                             {{ phase: 'Work' }})

// CRITIQUE: each critic independently tries to REJECT against the oracle rubric.
const verdicts = (await parallel(
  Array.from({{ length: CRITICS }}, (_, i) => () =>
    agent(`Critic ${{i + 1}}: adversarially grade this artifact against ${{ORACLE_CHECK}}. ` +
          `Default to approved=false on any doubt.\n\n${{artifact}}`,
          {{ phase: 'Critique', schema: VERDICT_SCHEMA }}))
)).filter(Boolean)

const approvals = verdicts.filter((v) => v.approved).length
const survived = approvals * 2 > verdicts.length

return {{ goal_id: GOAL_ID, survived, approvals, critics: verdicts.length,
         artifact: survived ? artifact : null }}
"
    )
}
