//! Hash and ordered map recommendations.

use super::workload::{AlgoRecommendation, WorkloadClass};

pub(super) const MAPS: &[AlgoRecommendation] = &[
    AlgoRecommendation {
        class: WorkloadClass::PointLookup,
        algo: "HashMap (SwissTable / hashbrown)",
        crate_name: "std::collections::HashMap",
        when: "Point key->value reads dominate; no range/order needed; keys hash well.",
        avoid_when: "Need ordered iteration, range queries, or deterministic memory layout; adversarial keys without DoS-resistant hasher.",
        complexity: "O(1) avg / O(n) worst (with bad hasher)",
        edge_cases: "Empty map; single bucket collisions; rehash storm at load factor; tombstone reuse with delete-heavy.",
        source: "https://doc.rust-lang.org/std/collections/struct.HashMap.html",
    },
    AlgoRecommendation {
        class: WorkloadClass::HashIntKey,
        algo: "FxHashMap / aHash / FoldHash",
        crate_name: "rustc-hash | ahash | foldhash",
        when: "Internal map keyed by integers/pointers; no untrusted input; need ~2x speedup.",
        avoid_when: "User-supplied keys (DoS); cross-process hash stability needed.",
        complexity: "O(1) avg, lower constants than SipHash",
        edge_cases: "Hash quality on small int ranges (0..N); verify bucket distribution.",
        source: "https://docs.rs/rustc-hash/latest/rustc_hash/",
    },
    AlgoRecommendation {
        class: WorkloadClass::HashCryptoSafe,
        algo: "SipHash (default) / BLAKE3 for content addressing",
        crate_name: "std default | blake3",
        when: "Untrusted input keys; cryptographic content addressing; deduplication of bytes.",
        avoid_when: "Hot internal-only path where DoS is irrelevant.",
        complexity: "O(n) for content; O(1) per key for SipHash hashing",
        edge_cases: "BLAKE3 outperforms SHA-256 by 10x but verify endianness for cross-platform digests.",
        source: "https://github.com/BLAKE3-team/BLAKE3",
    },
    AlgoRecommendation {
        class: WorkloadClass::OrderedRangeQuery,
        algo: "BTreeMap",
        crate_name: "std::collections::BTreeMap",
        when: "Need .range(), ordered iteration, predecessor/successor, or first/last key.",
        avoid_when: "Only point lookups (use HashMap O(1) instead).",
        complexity: "O(log n) per op; B-tree branching factor 11 = cache-friendly",
        edge_cases: "Range with exclusive bounds; empty range; cursor invalidation under mutation.",
        source: "https://doc.rust-lang.org/std/collections/struct.BTreeMap.html",
    },
    AlgoRecommendation {
        class: WorkloadClass::SetMembership,
        algo: "HashSet",
        crate_name: "std::collections::HashSet",
        when: "Need exact 'is X present?' over set built once; n > ~32.",
        avoid_when: "n < ~16 (Vec::contains wins via cache locality); need ordered iteration.",
        complexity: "O(1) avg per query",
        edge_cases: "Hash collisions on adversarial input; iteration order non-deterministic.",
        source: "https://doc.rust-lang.org/std/collections/struct.HashSet.html",
    },
    AlgoRecommendation {
        class: WorkloadClass::ApproxMembership,
        algo: "Binary Fuse Filter (xorf)",
        crate_name: "xorf",
        when: "Memory-bound 'probably-present' over large static set; allow false positives.",
        avoid_when: "Set mutates frequently (filter is immutable); FP rate matters strongly.",
        complexity: "~9 bits/key, 3 lookups",
        edge_cases: "Construction failure on tiny sets (<~50); 0 false negatives — false positives only.",
        source: "https://docs.rs/xorf/latest/xorf/",
    },
    AlgoRecommendation {
        class: WorkloadClass::ApproxCardinality,
        algo: "HyperLogLog++ / UltraLogLog",
        crate_name: "hyperloglogplus | ultraloglog",
        when: "Need approximate count of unique items at low memory (~1.5KB for 2% error).",
        avoid_when: "Need exact count; cardinality < ~1000 (HashSet is fine).",
        complexity: "O(1) per insert; constant memory",
        edge_cases: "UltraLogLog is 30% better at same memory; merge across shards is associative.",
        source: "https://en.wikipedia.org/wiki/HyperLogLog",
    },
    AlgoRecommendation {
        class: WorkloadClass::Concurrent,
        algo: "DashMap / scc::HashMap",
        crate_name: "dashmap | scc",
        when: "Multi-writer concurrent map under tokio; lock striping.",
        avoid_when: "Single-thread (HashMap is faster); read-mostly snapshot semantics (use ArcSwap<HashMap>).",
        complexity: "O(1) avg per op; lock contention proportional to shard count",
        edge_cases: "Iterator holds shard locks; do not .await across iter; deadlock if entry().or_insert with reentrant fn.",
        source: "https://docs.rs/dashmap/latest/dashmap/",
    },
    AlgoRecommendation {
        class: WorkloadClass::PersistentImmutable,
        algo: "im::HashMap (HAMT) / rpds::Vector (RRB-tree)",
        crate_name: "im | rpds",
        when: "Snapshot semantics; structural sharing across versions; undo/redo.",
        avoid_when: "Mutate-in-place is fine.",
        complexity: "O(log n) effective for HAMT; persistent updates",
        edge_cases: "Structural sharing means clone() is cheap; equality compares by structure.",
        source: "https://docs.rs/im/latest/im/",
    },
];
