//! Workload classification and recommendation structures.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum WorkloadClass {
    PointLookup,
    OrderedRangeQuery,
    TopK,
    SetMembership,
    ApproxMembership,
    ApproxCardinality,
    StreamingQuantile,
    PriorityQueue,
    Lru,
    Lfu,
    StringSearchSingle,
    StringSearchMulti,
    PrefixSearch,
    NearestNeighbor,
    SequentialScan,
    FifoQueue,
    LifoStack,
    DequeBoth,
    SortStable,
    SortUnstable,
    SortPartial,
    GraphTraversal,
    ShortestPathSparse,
    ShortestPathDense,
    ShortestPathRoadNet,
    ShortestPathAStar,
    AllPairsShortestPath,
    Mst,
    SccDfs,
    UnionFind,
    Concurrent,
    PersistentImmutable,
    HashIntKey,
    HashCryptoSafe,
    Compression,
    StringHash,
    Pagination,
    DistinctCount,
    RangeMin,
    PointUpdateRangeQuery,
    Dedup,
    Recursion,
    // ---- 2026 backend-at-scale tier ----
    RateLimiterPerKey,
    RateLimiterDistributed,
    ConsistentHashing,
    ShardingHotKey,
    Crdt,
    ReplicationGossip,
    LeaderElection,
    Idempotency,
    Deduplication,
    Backpressure,
    FanOut,
    FanIn,
    CircuitBreaker,
    RetryWithBackoff,
    EventOrdering,
    StreamWindow,
    CountMinSketch,
    BloomCounting,
    ChangeDataCapture,
    Saga,
    GeoLookup,
}

#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct AlgoRecommendation {
    pub class: WorkloadClass,
    pub algo: &'static str,
    pub crate_name: &'static str,
    pub when: &'static str,
    pub avoid_when: &'static str,
    pub complexity: &'static str,
    pub edge_cases: &'static str,
    pub source: &'static str,
}
