//! Classic destructive shell-op rows. `RawRow` = `(category, severity, name, fix,
//! regex-source)`; the parent compiles each via `Regex::new`.
use super::RawRow;
use crate::destructive_cli_guard::DestructiveCategory as C;
use crate::destructive_cli_guard::DestructiveSeverity::{P0Block, P1Confirm};

pub(super) const ROWS: &[RawRow] = &[
    (
        C::FilesystemNuke,
        P0Block,
        "rm-rf-root",
        "rm -rf at filesystem root or HOME deletes everything. Refuse.",
        r"(?i)\brm\s+(?:[a-z]+\s+)*-[a-z]*r[a-z]*f[a-z]*\s+(?:--no-preserve-root\s+)?(?:/(?:\s|$|\*)|~(?:\s|$|/)|/etc(?:\s|$|/)|/usr(?:\s|$|/)|/bin(?:\s|$|/)|/var(?:\s|$|/)|/home(?:\s|$|/?\*?$))",
    ),
    (
        C::DangerousFlag,
        P0Block,
        "no-preserve-root",
        "--no-preserve-root disables the kernel safety. Refuse.",
        r"(?i)--no-preserve-root",
    ),
    (
        C::PermissionsWipe,
        P0Block,
        "chmod-777-recursive",
        "chmod -R 777 destroys all permission boundaries. Refuse.",
        r"(?i)\bchmod\s+(?:[a-z]+\s+)*-[a-z]*r[a-z]*\s+(?:[ugoa+=,-]*)?7{3}\b",
    ),
    (
        C::PermissionsWipe,
        P0Block,
        "chmod-777-system",
        "chmod 777 on system path. Refuse.",
        r"(?i)\bchmod\s+(?:[ugoa+=,-]*)?7{3}\s+(?:/|/etc|/usr|/bin|/var|/root)",
    ),
    (
        C::PermissionsWipe,
        P0Block,
        "chown-recursive-system",
        "chown -R on / or system path destroys ownership boundaries. Refuse.",
        r"(?i)\bchown\s+(?:[a-z]+\s+)*-[a-z]*r[a-z]*\s+\S+\s+(?:/|/etc|/usr|/bin|/var|/root)\b",
    ),
    (
        C::DiskOverwrite,
        P0Block,
        "dd-to-disk",
        "dd to a block device overwrites data unrecoverably. Refuse.",
        r"(?i)\bdd\s+.*\bof=/dev/(?:sd[a-z]+|nvme\d+n\d+|hd[a-z]+|disk\d+)",
    ),
    (
        C::DiskOverwrite,
        P0Block,
        "dd-from-noise",
        "dd from /dev/zero or /dev/random into a block target. Refuse.",
        r"(?i)\bdd\s+.*\bif=/dev/(?:zero|random|urandom)\s+.*\bof=/dev/",
    ),
    (
        C::DiskOverwrite,
        P0Block,
        "filesystem-format",
        "mkfs/fdisk/parted reformats a disk. Refuse.",
        r"(?i)\b(?:mkfs|fdisk|parted)\S*\s+.*?/dev/",
    ),
    (
        C::ForkBomb,
        P0Block,
        "fork-bomb",
        "Classic fork bomb collapses the system. Refuse.",
        r":\s*\(\s*\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:",
    ),
    (
        C::KernelModule,
        P0Block,
        "kernel-module",
        "Loading/unloading kernel modules can crash the host. Refuse unless explicitly authorized.",
        r"(?i)\b(?:insmod|rmmod|modprobe\s+-r)\b",
    ),
    (
        C::HistoryScrub,
        P1Confirm,
        "history-scrub",
        "Clearing shell history scrubs the audit trail. Confirm explicitly.",
        r"(?i)\b(?:history\s+-c|cat\s+/dev/null\s*>\s*~?/?\.bash_history|export\s+HISTSIZE\s*=\s*0|unset\s+HISTFILE)\b",
    ),
    (
        C::PipeToShell,
        P0Block,
        "pipe-to-shell",
        "Piping arbitrary download to shell = remote code exec. Refuse.",
        r"(?i)\b(?:curl|wget|fetch)\s+[^|]*\|\s*(?:sudo\s+)?(?:bash|sh|zsh|/bin/(?:bash|sh|zsh))\b",
    ),
    (
        C::PrivilegeEscalation,
        P1Confirm,
        "sudo-rm-rf",
        "sudo combined with rm -rf escalates blast radius. Confirm.",
        r"(?i)\bsudo\b[^|]*\brm\s+-[a-z]*r[a-z]*f",
    ),
    (
        C::SystemHalt,
        P1Confirm,
        "system-halt",
        "Halting/rebooting drops in-flight requests. Confirm.",
        r"(?i)\b(?:shutdown\s+(?:now|-h|-r)|reboot|init\s+[06]|poweroff|halt)\b",
    ),
    (
        C::PipeToShell,
        P0Block,
        "reverse-shell-nc",
        "nc -e / ncat -e launches reverse shell. Refuse.",
        r"(?i)\b(?:nc|ncat|netcat)\s+(?:[a-z]+\s+)*-e\s+\S+",
    ),
    (
        C::HexObfuscation,
        P1Confirm,
        "hex-obfuscation",
        "Hex-encoded payload likely hides destructive intent. Confirm.",
        r"(?i)\\x[0-9a-f]{2}(?:\\x[0-9a-f]{2}){4,}",
    ),
    (
        C::DangerousFlag,
        P1Confirm,
        "chattr-immutable",
        "chattr changes immutable bit; can lock or unlock critical files. Confirm.",
        r"(?i)\bchattr\s+[+\-]i\b",
    ),
    (
        C::FilesystemNuke,
        P0Block,
        "mv-to-devnull",
        "mv to /dev/null silently destroys files. Refuse.",
        r"(?i)\bmv\s+\S+\s+/dev/null\b",
    ),
    (
        C::PermissionsWipe,
        P0Block,
        "etc-passwd-overwrite",
        "Redirecting into /etc/passwd or /etc/shadow corrupts auth. Refuse.",
        r"(?i)>\s*/etc/(?:passwd|shadow|sudoers)\b",
    ),
];
